version: '3'
services:
  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    networks:
      - warehouse-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  warehouse-network:
      driver: bridge

volumes:
  postgres_data:
