version: '3'
services:
  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    networks:
      - warehouse-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  clustered_data_warehouse:
    image: ahmd66699/clustered-data-warehouse:1.0.0-SNAPSHOT
    ports:
      - "8080:8080"
    networks:
      - warehouse-network
    depends_on:
      - postgresql

networks:
  warehouse-network:
      driver: bridge

volumes:
  postgres_data:
